### PR TITLE
funcionality to create a new match

### PR DESCRIPTION
**Pull request by olopez-accesso**
controller accepting json string and using existing service to create a match

### CODE REVIEW

**Comment by ssharp-accesso** [comment]
I did a quick review and it looks good to me.  Only thing I noticed is that you may want to switch the DB to point back to Test before merging it back in.

**Comment by olopez-accesso** [comment]
properties file updated

**Comment by danielneri-accesso** [comment]
One suggestion to make things a little easier with returning JSON - you could define a response transformer that will convert any object returned by the handler into JSON:

```java
get("/hello", "application/json", (request, response) -> {
    return new MyMessage("Hello World");
}, new JsonTransformer());
```

where JsonTransformer is essentially your utils class

for reference: http://sparkjava.com/documentation.html#response-transformer

**Comment by olopez-accesso** [comment]
It's used in a few places like RankingController:

```
        post("/ranking", (req, res) -> rankingService.createRanking(
                    req.queryParams("userId")),
            JsonUtil.json());
```

but if we want to perform specific operations or check if the object ==null for certain services, like this one:

```
        get("/users/:id", (req, res) -> {
            User user = userService.getUserData(req.params(":id"));
                if (user == null)
                {
                    res.status(HttpStatus.NOT_FOUND_404);
                    return "User not found";
                }
                else
                {
                    return JsonUtil.toJson(user);
                }
            });
```

I'm not sure if using the ResponseTransformer would help in these cases.

**Pull request merged**
